Extravi/araa-search

- __init__.py
- _config.py
If you search for a string like "hello world", you get a wikipedia page with the title path `%22Hello%2C_World%21%22_program`. All the escaped characters don't look good, and aren't very readable.
This PR just quotes that, so instead of being `%22Hello%2C_World%21%22_program`, it's `"Hello,_World!"_program`
This PR also gives an easier way to change the length of the cookie's age.
> Unquote result links

- __init__.py
Entering a search bang (no matter if it's an invalid or valid search bang, e.g. `!g ` or `!bangdoesnotexist`) will cause an error 500 as long as there's no query after the said bang.
This PR fixes that.
> Fix error 500 when there is no query after a search bang.

- static/css/style.css
- static/script.js
If material icons could not be loaded (either by the server not having the icons or the client rejecting them), "tune" would appear in-place of the settings icon (the one to the right of the search bar).
This PR fixes that bug by hiding that icon's name (with every other icon that is usually hidden) if the icons could not be loaded. It does this by hiding every element in the `material-icons-round` CSS class, only showing elements in that class when the pack could be loaded.
> Change how icons are loaded/hidden, fixed a bug with the settings icon when material icons could not be loaded.

- .gitignore
In response to https://github.com/Extravi/tailsx/commit/85b10c282cf3f04877c4f22b1b048022c99096f6. `.gitignore` will now tell git to ignore the `__pycache__` directory, regardless of where it lives.
> Always ignore `__pycache__` directory, regardless of location.

- templates/results.html
When you click on the buttons at the bottom of the page, it removes the search type. 
For example, if you're on the `reddit` search type and click the buttons at the bottom, it sends you to the default search type, which is `text`.
> Keep the type of search with the Next and Previous buttons at the bottom of the results page.

- static/calculator.js
- Pressing '.' will not overwrite a 0 (i.e. you will now see '0.xxx' instead of '.xxx')
- CE outputs 0 instead of blanking the output
- Error is returned on an unknown operation
> Fix a bug with how expressions were evaluated & improve outputs (see comment)

- templates/results_layout.html
First commit stops `calculator.js` from loading unless it's needed.
The second fixes a syntax error in how the opensearch.xml file is loaded.
> Only load calculator.js if it's needed

- _config.py
- src/torrent_sites/nyaa.py
- src/torrent_sites/torrentgalaxy.py
- src/torrents.py
- templates/torrents.html
I haven't tested whether torrent galaxy works with this, since I my ISP blocks all its domains, and I don't have a VPN. I haven't changed much of its code, mainly just replacing the `results` array with a dict. So please do check if it still works.
The main change is that it's now easier to add new torrent sites (see nyaa.py), so the torrent page isn't solely dominated by one site.
> Add nyaa.si for torrents, and make it easier for adding new torrent sites in the future.

- src/images.py
- src/textResults.py
- src/torrents.py
- src/video.py
If you search something like `& bitwise operator`, it doesn't work, since it thinks that `&` is adding an extra URL parameter. This fixes it by quoting it.
It also prevents a lot of XSS attacks, since the user doesn't control the URL that the server requests.
> Quote search query

- .env
- .gitignore
- Dockerfile
- compose.yaml
- scripts/docker-cmd.sh
- scripts/generate-opensearch.sh
- I've now published a remote docker image you can find [here](https://hub.docker.com/r/temthelem/tailsx).
- `docker-compose` now uses said image.
- Use of `.env` to set variables for a docker container without needing to rebuild.
Side note; I will rewrite the [docs](https://github.com/TEMtheLEM/tailsx-docs) to reflect these changes. Just a reminder that I am _still_ looking for feedback on the first round of changes I've proposed. I ask if you could look into those.
Cheers.
> Major Docker Changes (read comment)

- __init__.py
- _config.py
- src/helpers.py
- src/torrent_sites/nyaa.py
- src/torrent_sites/rutor.py
- src/torrent_sites/thepiratebay.py
- src/torrent_sites/torrentgalaxy.py
- src/torrents.py
This PR adds rutor and thepiratebay as extra torrent search engines.
I haven't been able to test if this works, since I don't have a VPN and my ISP blocks torrent sites, so please check if it does work.
> Add rutor & thepiratebay for torrent results

- __init__.py
- requirements.txt
- static/css/style.css
- static/quickAnswers.js
- templates/results_layout.html
This is in response to  #78.
This uses brave search's AI answer feature to get AI answers to queries.
Here's an example: https://imgur.com/AqJEWsH
It highlights the reference(s) when you hover over a piece of the text, and vice versa.
Do note that it isn't instant, because it uses a JS fetch in the browser, after the page has been rendered. It's done this way to stop it from interfering with the speed of the backend rendering of the page.
> Add AI answer feature for quick answers

- __init__.py
- src/torrents.py
- static/calculator.js
- static/script.js
- templates/results.html
- BUG FIX: Suggestions were not being quoted, causing queries like "c++ hello world" to show suggestions for C;
- BUG FIX: Bang redirects were not being quoted, causing queries like "!g c++ compiler download" to redirect to Google with "c compiler download".
- BUG FIX: The calculator used to sometimes not remove characters from an expression when backspace is pressed. This was due to the expression sometimes containing spaces (ex. `"2 + 2 "` would become `"2 + 2"` when backspace was pressed).
- BUG FIX; Typing in an expression into the calculator with the keyboard is now consistent with using the virtual buttons in terms of functionality.
- BUG FIX; Using backspace to clear an equation will now mimic hitting the CE button; 0 will be output instead of nothing.
- QOL; Hitting the enter key …
> Fix multiple bugs + some QOL.

- static/css/style.css
Before, the mobile torrent sort options had a margin to the left when on mobile, which made it all overflow.
This just removes that.
> Fix torrent select on mobile

- __init__.py
- src/helpers.py
- src/images.py
- src/textResults.py
- src/torrents.py
- src/video.py
- templates/discover.html
- templates/images.html
- templates/preresults_layout.html
- templates/results.html
- templates/results_layout.html
- templates/search.html
- templates/settings.html
- templates/torrents.html
- templates/videos.html
This PR moves all the settings into a single class.
The reason behind it is that if you currently want to add another setting, you'll have to change several files, which can be very time consuming.
The way that the `render_template`s are formatted at the end of each function isn't very readable, so this helps to reduce its size.
If you've got no knowledge of the codebase, and are reading through any of the template files, this PR helps in making things more readable, as all settings begin with `setting.`.
Also, if there's ever any vulnerabilities that come from the cookies, it'll now be 10x easier to perform validation on the cookies.
> Move all settings into one class

- src/images.py
- static/css/catppuccin_mocha_blue.css
- static/css/catppuccin_mocha_green.css
- static/css/classic.css
- static/css/dark.css
- static/css/dark_blur.css
- static/css/dark_default.css
- static/css/darker.css
- static/css/gentoo_lavender.css
- static/css/github_night.css
- static/css/light.css
- static/css/night.css
- static/css/red.css
- static/css/style.css
- static/script.js
- templates/images.html
This is a duplicate of #96 because I forgot to change my global git email.
Here's the original text:
This PR does a few things to improve the image page.
It simplifies the images.py and images.html code, so that it's a lot more easier to read.
It adds a title and domain to all of the images.
It adds a box around the selected image.
And it adds a box in the bottom left showing the resolution of the original image.
It also shows the a link to the full size image in when you open the image menu.
These changes are mainly based on qwant's image page, since I think that looks quite good.
> Improve image page design

- __init__.py
- src/images.py
Qwant gets their images from bing, then proxies it themselves.
This PR removes qwant's proxy, so instead of going
bing -> qwant -> araa -> user
it goes
bing -> araa -> user
Which decreases the time taken to proxy the image.
> Improve proxy speed

- scripts/generate-pyconfig.py
- static/script.js
- templates/images.html
The image viewer claims to allow users to view an image through the proxy, when it really redirects users to an unproxied link to the image;
the circled text links to `http://www [dot] diapason-info [dot] com/...` with the rest or the URL being the path to the image, rather than the instance's proxy.
This PR corrects this issue while also adding a separate option to view the image through the instance's proxy;
Note that proxied images are lower res, hence why it's given as an alternative option.
Side note: Is there any reason why the image proxy still only allows certain URLs? I was able to get it set up so users can use it to view the full res images, but that only works if the proxy can load images from any URL. May want to look into this in the future.
> Add `DEFAULT_METHOD` to auto-generator for `_config.py`. Fix an issue with the image viewer (read desc).

- __init__.py
- _config.py
- src/helpers.py
- static/lang/README.md
- templates/settings.html
This adds a constant in _config.py, where you can easily add text for displaying the language in the settings page.
In both #88 and #118, the contributors forgot to add it to the settings.html file. This PR will probably make it easier to do so for people who haven't got knowledge in html, or otherwise didn't think to add it.
I've also added a readme file with some instructions, which might help people who add languages in the future.
> Make it easier to add new languages

- __init__.py
When you refresh araa, the browser grabs everything (such as fonts, and css files).
This PR changes it so that the browser will only request the data once every hour.
I've chosen once an hour to allow for changes to the files.
This will make the experience with switching search types a lot nicer, and also decrease server load.
> Add caching.

- __init__.py
- static/css/style.css
- static/script.js
- templates/results_layout.html
- templates/search.html
This adds a button in the search input field that lets you clear the results. It only shows for JS users because there's no way to clear an input without JS.
This also makes clicking on the search field automatically show the suggestions.
> Add clear search button and show suggestions on input focus

- src/textResults.py
On google, in the snippets, you can usually click on words/names to get more info on it. This is included when you run `snip = featured_snip.text.strip()`.
This PR removes those elements, so they don't come up in the results.
Before:
After:
> Stop googles extra text from showing in the snippet

- static/cookies.js
When changing the theme, the entire page shouldn't reload.
This PR makes it so that instead of reloading the whole page when a different theme is selected, only the `link` element which holds the theme's location is changed.
This makes for a smoother, and more efficient way to change theme.
> Dont refresh after changing the theme

- src/video.py
In the Screenshots in README.md, the videos tab shows videos with lengths of 480 minutes, instead of 8 hours.
This PR fixes that, so instead of `480:00`, you get `08:00:00`
> Fix broken durations for videos longer than 1 hour

- src/textResults.py
- static/css/style.css
- templates/results.html
If you use a theme like the windows 95 theme from the discover themes section in settings, there's always an empty box under the first result. It's there for the sublinks, but when sublinks aren't there, it's not needed.
This PR removes that div, unless it's needed.
> Remove empty results div under first result.

- static/script.js
If you select an image, then use the arrow keys, the image changes.
This PR stops that from happening
> Dont change image when input is focused

- static/script.js
If you use the arrow keys to change an image, the page doesn't scroll to put that image into focus.
This PR makes the page scroll to put the image that's selected into view.
> scroll current image into view

- src/text_engines/qwant.py
Qwant wiki descriptions have citation numbers in them:
This PR removes them.
> Remove citations from wiki desc

- src/text_engines/google.py
Google has updated the wiki format, which causes there to be no wiki snippets.
This PR just renames some classes to fix it.
> Fix updated wiki

- __init__.py
- _config.py
- src/helpers.py
- src/textResults.py
- src/text_engines/google.py
- src/text_engines/qwant.py
- static/cookies.js
- static/css/style.css
- static/script.js
- templates/results.html
- templates/settings.html
This adds an option to change between either qwant or google. This will be quite useful for in the future if we decide to add any more engines.
It also adds a date filtering option, which closes #174.
> Add engine filter option and date range for google
