__init__.py
templates/images.html

Some reformatting, HTML requests can be made in a separate function to reduce code repetition, redo of how '/search' works and a conceptualized image page.

"Minor" changes, see comment.

---

__init__.py
templates/images.html

Enhanced images page.

---

__init__.py
templates/images.html
templates/results.html
templates/results_layout.html
templates/search.html
templates/settings.html

Cleanup includes;
-> creating a common layout for search results to use
-> hitting enter on a few lines to reduce how long some lines were
Search results (text and images) also have a var 'type' which stores what type the results are.
This var is needed.
lmk if you have issues

Code cleanup, see comment.

---

REPOSITORY
__init__.py
templates/results_layout.html
templates/search.html
templates/settings.html

Some manual editing should be done in `/REPOSITORY`, fyi.

Commit id shown on webpage & Security policys

---

__init__.py

Typing !ddg will redirect your search query to DuckDuckGo, !g to Google, etc.
Change the bang by reassigning `BANG=...`, and add/remove engines OR change their bang patterns with `SEARCH_BANGS = [...]`

Search bangs

---

README.md

https://tailsx.com
A+ SSL labs.
Runs in Toronto, Canada.
May TailsX live on.

Add another instance to the instance list

---

__init__.py
static/css/style.css
templates/results.html

Changes _should_ work fine. The replaced commits are mentioned in their replacements.
**This merge will remove all recent commits up to & including the one where Powershell thought it would be nice to end every file with `\r\n`.**

Scrap previous 3 commits for 2 cleaner ones.

---

__init__.py
static/css/style.css
templates/results.html
templates/settings.html

If you submit the settings form, you get sent to a 404 not found page.
This PR sends the user back to the url they were at before.

Send user back to page they were previously on after submitting their settings.

---

__init__.py
static/css/style.css
templates/results.html
templates/settings.html
templates/videos.html

Add option to open links in new tabs.

---

__init__.py
_config.py
src/helpers.py
src/images.py
src/textResults.py
src/torrents.py
src/video.py

#38, but without the merge conflicts.

Structure files2

---

.gitignore
static/calculator.js
templates/results.html

- PEDMAS properly works (no exponents or parenthesis yet)
- Parser properly determines if numbers are actually numbers using `isNaN()`
- "0" will be completely replaced when the user starts putting in numbers (looks better)
- `calculator.js` uses the same indentation as `script.js` now (consistency!)

Calculator improvements

---

src/textResults.py
static/calculator.js
static/css/style.css
templates/results.html

Here's what this calculator looks like:
Its design is much more inline with how most real calculators will look, with 3 nums on each row, counting from lowest to highest. I've done this using `display: grid;`, so upgrading to add more columns for functions will be a lot easier.
This also includes support for parenthesis/brackets.
Its got a line to show what the equation was that gave you the current result.

Parenthesis support, history, and design change for the calculator

---

__init__.py
static/calculator.js
static/script.js

This makes pressing keyboard keys do the same thing as pressing the keys on the calculator.
Also, I made the image javascript code only apply if you're in the images tab, which stops some error messages.

Keypress support for calculator & only load the image viewer code if you're in the images tab.

---

src/images.py

This makes the safesearch option in the settings also effect images.

Add safe search option for images

---

__init__.py

See [#69](https://github.com/Extravi/araa-search/issues/69#issuecomment-1756347345)

adjusted bang redirects

---

.env
Dockerfile
__init__.py
compose.yaml
resources/_config.py.gen.template
scripts/generate-pyconfig.py
src/helpers.py
src/images.py

`search()` was essentially only running any code if the request's method was `GET`. So I moved all of the code outside of that one if statement and simply made the function return an error if `GET` is not used.
The Docker image now contains some useful metadata. It's also updated for the new config.
And finally, using `docker-compose`, users can have their containers automatically update any time a new image is pushed to Docker Hub.

Minor reformat to `search()` (read comment). Docker image updated to support new config vars. Watchtower is now used to auto-update docker containers.

---

__init__.py
_config.py
src/video.py
templates/videos.html

- Thumbnails are now clickable
- Fixed the issue when using a different Invidious instance 
You can test the changes on my instance.

Minor tweaks to videos

---

static/lang/romanian.json

Guessing it's the right place to contribute? 
either way, it's translated. I don't have much to say but, have a great day. 😄

Translation for Romanian

---

src/torrent_sites/nyaa.py
src/torrent_sites/rutor.py
src/torrent_sites/thepiratebay.py
src/torrent_sites/torrentgalaxy.py
src/torrents.py
static/css/style.css
templates/torrents.html

This adds an option to only search for specific catagories, such as movies, games, or audiobooks.
It also blocks porn torrents when the user has safe-search enabled.

Add catagory option for torrents

---

__init__.py
_config.py
src/helpers.py
src/images.py
src/textResults.py
src/torrents.py
src/video.py
templates/images.html
templates/results.html
templates/results_layout.html
templates/search.html
templates/settings.html
templates/torrents.html

This PR adds an option in the settings to use the POST method.
The only issue I've found with this is that the settings at the top of the Web results page doesn't redirect you back to the results you were previously on. If no one can come up with a better solution, I'll just make an if statement to only show it for GET users. This isn't a massive problem, since the settings at the top can still be changed within the settings page.

Add post method

---

_config.py
src/helpers.py
src/torrent_sites/nyaa.py
src/torrent_sites/rutor.py
src/torrent_sites/thepiratebay.py
src/torrent_sites/torrentgalaxy.py
src/torrents.py
static/css/style.css
templates/torrents.html

This PR adds a link under each torrent that links to the original post for the torrent. This is useful for if you're downloading software and want to check if the person who made the torrent is well known and trusted.
A lot of the PR is also just changing a few things so that they conform with the PEP 8 style guide, so that my editor stops giving me tons of errors.

Add view source button to torrents

---

_config.py
scripts/generate-pyconfig.py
src/torrent_sites/torrentgalaxy.py
src/torrents.py

Reverts Extravi/araa-search#124

Revert "remove torrentgalaxy"

---

src/textResults.py
static/css/style.css
templates/results.html

Change wiki snippet ui

---

__init__.py
static/uxlang.js

The default language is English, so there's no need to reload the page if the language is English.

Only refresh if language isn't english

---

__init__.py

Language specifict search suggestions

---

__init__.py
src/helpers.py
static/css/style.css
templates/results_layout.html
templates/settings.html

Add option in settings to disable torrent search
